theme: jekyll-theme-cayman
.sidenav {
  height: 100%;
  width: 350px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: navy;
  overflow-x: hidden;
  padding-top: 20px;
}
.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: gray;
  display: block;
}
.sidenav a:hover {
  color: lightgray;
}
.main { 
  margin-left: 350px;
  padding: 2px 10px;
}

